stack_space_size = 0x2000
stack_size = 0x1000
platform = "ArmV8m"

[regions]
flash = { address = 0x08000000, size = 0x80000 }
ram = { address = 0x20000000, size = 0x40000, role = "stack" }

[probe]
chip = "STM32L562QEIxQ"

[kernel]
crate_path = "./"
stack_size = 0x00004
sizes.ram = 0x20000
sizes.flash = 0x20000

[[tasks]]
name = "idle"
crate_path = "../idle"
secure = false
root = false

[[tasks]]
name = "foo"
crate_path = "../foo"
secure = false
root = false


[[tasks]]
name = "bar"
crate_path = "../bar"
secure = false
root = false
