name: Deploy to GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website
      - name: Build website
        run: yarn build
        working-directory: ./website
      - name: Deploy to branch
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ./website/build
